server:
  port: 80
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/isb?currentSchema=infinity_stack
    username: isb
    password: isb_password
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

